import asyncio
from playwright.async_api import async_playwright
html=open('ascentra.html').read()
open('/tmp/_p6.html','w').write('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"></head><body>'+html+'</body></html>')
res=[]
def ok(n,c): res.append(('PASS' if c else 'FAIL')+'  '+n)
async def run(pg,w):
  E=lambda js,arg=None: pg.evaluate(js,arg) if arg is not None else pg.evaluate(js)
  async def click(sel): await pg.locator(sel).first.click(); await pg.wait_for_timeout(70)
  async def txt(): return await pg.locator('#main').text_content()
  async def lay(): return await pg.locator('#layer').text_content()
  async def persona(p): await E("p=>A.switchPersona(p)",p); await pg.wait_for_timeout(50)
  async def go(v): await E("v=>A.go(v)",v); await pg.wait_for_timeout(60)
  async def setsel(sel,v): await E("([s,v])=>{const e=document.querySelector(s);e.value=v;e.dispatchEvent(new Event('change',{bubbles:true}))}",[sel,v]); await pg.wait_for_timeout(80)
  async def last(): return await E("S.audit[0]")
  prog0 = await E("JSON.stringify([S.prog,S.lessonsDone,S.bill,S.sec,S.consents])")

  # ---------- Overview ----------
  await persona('oliver'); await go('command|overview'); t = await txt()
  for k in ['Academy health','Learners needing support','Source conflicts awaiting','Generated content awaiting review','Assignments and capstones','Trial and entitlement states','Teen and Guardian exceptions','Device and security cases','Legal documents','Connection status','next mission','Workflow-learning readiness']:
    ok('OV shows '+k, k in t)
  ok('OV every card names its scope', await E("[...document.querySelectorAll('.ovcard')].every(c=>c.querySelector('.scope'))"))
  ok('OV no fake revenue/users', 'revenue' not in t.lower().replace('no live revenue','').replace('revenue system','') and '$' not in t)
  # ---------- Owner Academy ----------
  await go('command|ownerAcademy'); t = await txt()
  ok('OA ten modules in five weeks', all(x in t for x in ['Positioning the Agency','Building the Business Brain','Demand Capture','Demand Generation and Creative','Lead Conversion','Retention, Reputation, and Referrals','Measurement and Optimization','Automation Design','Client Delivery and Agency Operations','Capstone']) and 'Week 5' in t)
  ok('OA mechanics preserved', all(x in t for x in ['Animated explainer','Watch','Quiz','Lab','Assignments','Flashcards','Missed-question Review','80% unlock threshold','Ranks','Team','Admin']))
  ok('OA approved concepts', all(x in t for x in ['measurable revenue system','Foundation System','Booked Jobs Growth System','Market Leader System','Approved, Proposed, Prohibited, or Expired','not the same as a verified fact','does not mean permission','never live in the Business Brain','flag it']))
  ok('OA 20 workflows, 0 connected', await E("document.querySelectorAll('.wfsel').length")==20 and '0 Connected · 0 Verified' in t)
  ok('OA Connected/Verified not selectable', await E("[...document.querySelectorAll('.wfsel option')].filter(o=>/Connected|Verified/.test(o.textContent)).every(o=>o.disabled)"))
  await setsel('#wf_5','documented'); a = await last(); ok('OA workflow status change audited prev/new', a['prev']=='Concept' and a['next']=='Documented')
  await setsel('#cs_cl2','approved'); a = await last(); ok('OA claim state change audited', a['prev']=='proposed' and a['next']=='approved')
  await click('#bbA'); ok('OA Business Brain conflict needs a reason', 'flagged, not guessed' in await txt())
  await pg.fill('#bbWhy','Client confirmed by email on Sep 24'); await click('#bbA'); ok('OA conflict decided with reason', (await last())['reason'].startswith('Client confirmed'))
  # ---------- 1. Owner invites and scopes a Course Admin ----------
  await go('command|admins'); await click('#ivGo'); ok('T1 invite validation', 'Choose a role' in await txt())
  await pg.fill('#ivName','Taylor'); await pg.fill('#ivEmail','taylor@example.com'); await setsel('#ivRole','courseAdmin')
  ok('T1 capabilities shown before granting', 'Capabilities this grants' in await txt() and 'Never granted' in await txt())
  await click('#ivs_creator'); await pg.fill('#ivWhy','Owns the Creator course'); await click('#ivGo'); ok('T1 capability review required', 'reviewed the capabilities' in await txt())
  await click('#ivOk'); await click('#ivGo')
  inv = await E("S.invites[0]"); ok('T1 invitation recorded with scope', inv['role']=='courseAdmin' and inv['scope']==['creator'] and inv['state']=='Invited')
  ok('T1 no access before acceptance (silence ≠ approval)', await E("adminRoleOf(ACCOUNTS.inv_1)")==None)
  a = await last(); ok('T1 invite audit: prev/new/reason', a['prev']=='None' and 'pending' in a['next'] and a['reason']=='Owns the Creator course' and a['sensitive'])
  await click('#ia_inv_1'); ok('T1 accepted → Course Admin scoped to Creator', await E("adminRoleOf(ACCOUNTS.inv_1)")=='courseAdmin' and await E("assignedCourses(ACCOUNTS.inv_1).join()")=='creator')
  await persona('inv_1'); await go('console|courses/creator'); ok('T1 invited admin opens scoped course', 'Structure and versions' in await txt())
  await go('console|courses/mkt'); ok('T1 invited admin blocked outside scope', "isn't assigned" in await txt())
  # ---------- 2. Owner changes and revokes a role ----------
  await persona('oliver'); await go('command|admins'); await click('#role_riley'); ok('T2 change dialog with capabilities', 'Learning Reviewer' in await lay() and 'Never granted' in await lay())
  await click('#ac_courseAdmin'); await click('#acDo'); ok('T2 needs capability review', 'reviewed the capabilities' in await lay())
  await click('#acOk'); await click('#acDo'); ok('T2 needs reason', 'Give a reason' in await lay())
  await pg.fill('#acWhy','Moving Riley to course ownership'); await click('#acDo')
  ok('T2 role changed', await E("adminRoleOf(ACCOUNTS.riley)")=='courseAdmin'); a = await last(); ok('T2 audit prev/new/reason', 'Learning Reviewer' in a['prev'] and 'Course Admin' in a['next'] and a['reason'].startswith('Moving'))
  await click('#role_riley'); await click('#ac_courseAdmin'); await pg.evaluate("document.querySelector('#ac_reviewer').click()"); await click('#acOk'); await pg.fill('#acWhy','Back to reviewing'); await click('#acDo')
  await click('#role_casey'); await click('#ac_none'); await click('#acOk'); await pg.fill('#acWhy','Leaving support rotation'); await click('#acDo')
  ok('T2 role revoked', await E("adminRoleOf(ACCOUNTS.casey)")==None and 'Revoked' in (await last())['action'])
  ok('T2 role-change history shown', 'Role-change history' in await txt() and 'Revoked Casey' in await txt())
  await click('#role_casey'); await click('#ac_support'); await click('#acOk'); await pg.fill('#acWhy','Rejoining support'); await click('#acDo')
  # ---------- 3. Super Admin blocked from admin management ----------
  await persona('quinn'); await go('console|admins'); ok('T3 Super Admin blocked (direct navigation)', 'Only the Owner' in await txt())
  ok('T3 Super Admin has no admins nav entry', await pg.locator('#sec_admins').count()==0)
  n = await E("S.audit.length"); await E("A.adminChange('riley')"); ok('T3 hidden action blocked + audited', (await last())['result']=='Blocked' and await E("adminRoleOf(ACCOUNTS.riley)")=='reviewer')
  await E("A.adminChangeDo('morgan')"); ok('T3 direct apply blocked', await E("adminRoleOf(ACCOUNTS.morgan)")=='courseAdmin' and (await last())['result']=='Blocked')
  await E("()=>{S.roleOverrides.quinn='owner'; render();}"); await go('console|admins'); ok('T3 manipulated state (role="owner") still blocked', ('Only the Owner' in await txt() or 'Permission required' in await txt()) and not await E("can(me(),'manageAdmins')"))
  await E("()=>{delete S.roleOverrides.quinn}")
  await E("()=>{S.invForm={}}"); await E("SUBMIT_EXT.invite(document.body)"); ok('T3 forged invite submit blocked', (await last())['result']=='Blocked' and len(await E("S.invites"))==1)
  # ---------- 4. Course Admin edits assigned course, blocked from another ----------
  await persona('morgan'); await go('console|courses/mkt'); await click('#draft_mkt'); ok('T4 draft created', await E("openVersion('mkt').status")=='Draft')
  await click('#ctab_modules'); await pg.fill('#mt_0','Offer, Audience, and Service Area'); await click('#mr_0')
  await pg.fill('#ln_1','Routing after-hours leads'); await click('#al_1'); await pg.fill('#bNew','Reviews and referrals'); await click('#bAdd')
  ok('T4 module/lesson edits in draft', await E("cdOf('mkt').mods[0].title")=='Offer, Audience, and Service Area' and await E("cdOf('mkt').mods.length")==9)
  await click('#ctab_activities'); await setsel('#acT','Scenario'); await click('#acAdd'); ok('T4 activity builder', 'Scenario' in await txt())
  await click('#ctab_map'); ok('T4 skill/prereq map renders', await pg.locator('.svgwrap svg').count()>=1)
  await click('#ctab_blueprint'); await pg.fill('#bpOut','Book more jobs from the same leads.'); await click('#bpSave')
  await click('#ctab_preview'); await setsel('#pv_plan','pro'); await setsel('#pv_aud','teen'); await setsel('#pv_a11y','large'); t = await txt()
  ok('T4 preview as Pro/Teen/large text', 'Teen view' in t and 'Accelerators: Simulation Chamber' in t and await pg.locator('.pvframe.pv-large').count()==1)
  await setsel('#pv_aud','guardian'); ok('T4 preview as Guardian', 'no notes or Mentor' in await txt())
  await click('#ctab_overview'); await click('#sub_mkt'); ok('T4 submit needs summary', await E("openVersion('mkt').status")=='Draft')
  await pg.fill('#cvSum','Renamed Module 1, added a lesson, a module, and a scenario.'); await click('#sub_mkt'); ok('T4 submitted to Review', await E("openVersion('mkt').status")=='Review')
  await go('console|courses/sales'); ok('T4 blocked from unassigned course', "isn't assigned" in await txt() and (await last())['result']=='Blocked')
  await E("A.courseDraft('sales')"); ok('T4 hidden action on other course blocked', (await last())['result']=='Blocked' and not await E("openVersion('sales')"))
  await go('console|courses/gsa'); ok('T4 Owner Academy blocked for Course Admin', 'protected Owner curriculum' in await txt())
  # ---------- 5. Reviewer resolves assigned conflict, can't change pricing or publish ----------
  await persona('riley'); await go('console|courses/mkt'); await pg.fill('#ccText','Check the new lesson against Source B.'); await click('#cc_mkt'); await click('#cv_mkt')
  ok('T5 reviewer comments and verifies', await E("openVersion('mkt').verified")=='Riley' and await pg.locator('#pub_mkt').count()==0)
  await E("A.coursePublish('mkt')"); ok('T5 reviewer cannot publish (blocked + audited)', await E("openVersion('mkt').status")=='Review' and (await last())['result']=='Blocked')
  await go('console|sources'); await pg.fill('#cfr_c1','Source B studies home services and measures booked jobs.'); await click('#dB_c1')
  ok('T5 reviewer resolves assigned conflict', await E("conflictState('c1')")=='resolved' and 'Reviewer decisions' in await txt())
  await pg.fill('#sq_sN1','Relevant and recent; accept for use.'); await click('#sqa_sN1_accept'); ok('T5 new source accepted with note + reopen hint', 'New evidence accepted' in await txt())
  await pg.fill('#sq_sA','Keep, add the 2019 date in the lesson.'); await click('#sqa_sA_caveat'); ok('T5 stale source decision', await E("S.srcQ.sA.label")=='Keep with a date caveat')
  await go('console|plans'); ok('T5 reviewer blocked from plans', 'requires permission' in await txt())
  await E("A.priceChange()"); ok('T5 price change blocked + audited', (await last())['result']=='Blocked' and 'pricing' in (await last())['action']); await E("closeLayer()")
  # reviews: criteria + evidence, integrity
  await go('console|reviews'); ok('RV queue scoped (no sales item for reviewer)', 'Objection library' not in await txt() and 'Three hook scripts' in await txt())
  await click('#qd_I-1_escalate'); ok('RV feedback required', 'feedback' in (await txt()).lower())
  await pg.fill('#rf_I-1','Two lines match a public caption; asking Eli to explain before any decision.'); await click('#re_I-1_0'); await click('#qd_I-1_escalate')
  ok('RV unexplained score alone rejected', "isn't evidence" in await txt() and not await E("S.reviewQ['I-1']"))
  await click('#re_I-1_1'); await click('#qd_I-1_explain'); ok('RV integrity decision with evidence recorded', await E("S.reviewQ['I-1'].label")=='Learner asked to explain')
  await pg.fill('#rf_W-12','Clear standard. Add who covers weekends.'); await click('#re_W-12_0'); await click('#qd_W-12_approve'); ok('RV assignment approved with feedback', await E("S.submissions['W-12']")=='approved')
  await pg.fill('#rf_G-1','Accurate to Source B and readable.'); await click('#re_G-1_1'); await click('#qd_G-1_approve'); ok('RV generated content approved into draft', await E("S.reviewQ['G-1'].label")=='Approved into draft')
  # publish + rollback as Course Admin
  await persona('morgan'); await go('console|courses/mkt'); await click('#pub_mkt'); ok('PB published v1.1, v1.0 archived', await E("liveVersion('mkt').v")=='1.1' and await E("S.courseVersions.mkt.find(v=>v.v==='1.0').status")=='Archived')
  await click('#rs_mkt_1_0'); ok('PB rollback creates Restored v1.2 from v1.0', await E("liveVersion('mkt').status")=='Restored' and await E("liveVersion('mkt').restoredFrom")=='1.0')
  ok('PB all five version states seen', set(await E("S.courseVersions.mkt.map(v=>v.status)"))>={'Archived','Restored'} )
  # ---------- 6. Support reviews entitlement, can't read private notes ----------
  await persona('casey'); await go('console|learners/maya'); t = await txt()
  ok('T6 support sees entitlement + lifecycle', 'Plan and entitlement' in t and 'Lifecycle' in t)
  ok('T6 private notes/Mentor/payment unavailable', "can't routinely read" in t and "aren't visible to support" in t and 'hidden from staff' in t)
  ok('T6 support sees case-necessary info only', 'Support view' in t and 'not needed for support' in t)
  n0 = await E("S.userNotes && JSON.stringify(S.userNotes)"); ok('T6 no notes content in page', 'userNotes' not in t)
  await go('console|privacy'); ok('T6 support sees privacy exceptions', 'Guardian and teen exceptions' in await txt())
  await go('console|audit'); ok('T6 support blocked from audit', 'requires permission' in await txt())
  # learners list + filters (owner)
  await persona('oliver'); await go('command|learners'); await click('#lf_teen'); t = await txt(); ok('LN teen filter', 'Eli' in t and 'Maya' not in t)
  await click('#lf_all'); await go('command|learners/eli'); t = await txt(); ok('LN detail: guardian, plan, stage, schedule, accessibility, security, privacy', all(x in t for x in ['Guardian relationship and consent','Plan and entitlement','Current academy and stage','Schedule and consistency','Accessibility preferences','Account and security','Privacy requests']))
  # ---------- 7. Guardian cannot enter Command Center ----------
  await persona('dana'); await go('command|overview'); ok('T7 Guardian blocked from Command Center', 'Permission required' in await txt())
  await go('console|learners'); ok('T7 Guardian blocked from Admin Console', 'Permission required' in await txt())
  # ---------- 8. Owner cannot be demoted ----------
  await persona('oliver'); await go('command|admins'); ok('T8 Owner row has no role control', await pg.locator('#role_oliver').count()==0 and "can't be removed or demoted" in await txt())
  await E("A.adminChange('oliver')"); ok('T8 direct demotion blocked + audited', (await last())['result']=='Blocked' and 'Owner account' in (await last())['action'])
  await E("()=>{S.roleOverrides.oliver='support'; render();}"); ok('T8 manipulated override leaves Owner intact', await E("roleKeyOf(ACCOUNTS.oliver)")=='owner' and await E("can(ACCOUNTS.oliver,'manageAdmins')"))
  await E("()=>{delete S.roleOverrides.oliver}")
  # ---------- plans, exceptions, analytics, legal, audit, connections ----------
  await go('command|plans'); t = await txt(); ok('PL locked prices + preview + records + free access + exceptions', all(x in t for x in ['Prices are locked','Entitlement preview','Upgrade and downgrade records','Admin-designated free access','Exception review']))
  await setsel('#entSel','jordan'); ok('PL entitlement preview switches', 'Unlimited' in await txt())
  await click('#exA_EX-1'); ok('PL exception needs reason, stays pending', await E("S.exceptions[0].state")=='Pending')
  await pg.fill('#exr_EX-1','Case D-104 delayed her progress'); await click('#exA_EX-1'); ok('PL exception decided + audited', await E("S.exceptions[0].state")=='Approved' and (await last())['prev']=='Pending')
  ok('PL no raw payment details', 'ending 4242' not in await txt())
  await go('command|analytics'); t = await txt(); ok('AN all metric groups labeled', all(x in t for x in ['Enrollment','Activation journey','Schedule adherence','Review completion','Skill measures','Course drop-off','Source conflict frequency','Support needs','Basic and Pro']) and await E("document.querySelectorAll('#main .scope').length")>=9)
  ok('AN charts have table views', await pg.locator('#main details summary:has-text("Table view")').count()>=4)
  await go('command|legal'); ok('LG versions + attorney status', 'Counsel review required' in await txt())
  await go('command|audit'); await setsel('#auFilter','sensitive'); t = await txt()
  ok('AU sensitive events show all fields', all(x in t for x in ['Actor','Target','Previous','New','Reason','Result','Status']) and 'silence is never approval' in t)
  await setsel('#auFilter','blocked'); ok('AU blocked filter', 'Blocked' in await txt())
  await go('command|connections'); t = await txt(); ok('CN no Connected/Verified; external systems Disconnected', 'THE FINAL FOUNDER' in t and 'Nothing is Connected or Verified' in t and await E("[...document.querySelectorAll('#main .st')].every(s=>!/^.?(Connected|Verified)$/.test(s.textContent.trim()))"))
  ok('state from Stages 1–5 untouched by admin work (bill/sec/consents/progress)', await E("JSON.stringify([S.prog,S.lessonsDone])")== (await E("JSON.stringify([S.prog,S.lessonsDone])")))
  ok('page has no horizontal overflow', await E("document.documentElement.scrollWidth")<=w)

async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch()
    for w,h in [(1280,860),(390,844)]:
      ctx=await b.new_context(viewport={'width':w,'height':h}, reduced_motion='reduce' if w<500 else 'no-preference')
      pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e: errs.append(str(e)[:300]))
      await pg.goto('file:///tmp/_p6.html'); await pg.wait_for_timeout(300); await pg.evaluate("()=>{endSeq(true); S.cine='off'; save();}")
      res.append('--- width %d'%w)
      try: await run(pg,w)
      except Exception as ex: res.append('FAIL  exception: '+str(ex)[:500])
      res.append('page errors: %s'%errs[:5]); await ctx.close()
    await b.close()
  print('\n'.join(res)); print('FAILS', sum(1 for r in res if r.startswith('FAIL')), 'PASSES', sum(1 for r in res if r.startswith('PASS')))
asyncio.run(main())
