import "server-only";
import { randomUUID } from "node:crypto";
import type { Account } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { ATTORNEY, NO_ATTORNEY, clean, isUuid, refused, type Result } from "./common";
import { academyOf, slotView } from "./owner-review";
import { canOpenCourse } from "./learn";
import { findIncomeClaims, textsOf } from "./income";
import { MIN_TRANSCRIPT_CHARS, VIDEO_LINK_SECONDS, VIDEO_MAX_BYTES, VIDEO_TYPES, sniffVideo, tooLarge, type VideoBrief, type VideoMime } from "./structure";
import { headOf, removeFile, signDownload, signUpload } from "./video-store";

/**
 * C1: video slots. Each slot says what its explainer video must cover (the brief, which the Owner can copy into the tool
 * they make videos with), takes the finished file (mp4 or webm, checked by its first bytes, 50 MB at most), needs a
 * transcript or captions, and is approved by the Owner. Files live in the private "course-videos" bucket. A learner
 * gets a link that works for ten minutes, only for an approved slot of a published course they may open; anything else
 * shows "Video coming". No video is generated by the app.
 */
type Slot = {
  id: string; module_id: string; lesson_id: string | null; position: number; title: string; brief: VideoBrief; brief_generated_by: string; status: string;
  current_upload_id: string | null; transcript: string | null; approved_at: string | null; approved_by_account_id: string | null; brief_edited_at: string | null;
};
type Upload = { id: string; slot_id: string; storage_path: string; mime: string; size_bytes: number; status: string; original_name: string | null; uploaded_by_account_id: string; uploaded_at: string; reject_reason: string | null; replaced_at: string | null };

const A = "courses.videos";
const OWNER_ONLY = "Only the Owner manages videos.";

/** The slot, if it belongs to this course (by slug), with its module and course version. */
async function slotIn(slug: string, slotId: string) {
  if (!isUuid(slotId)) return null;
  const db = getDb();
  const slot = (await db.from("video_slots").select("*").eq("id", slotId).maybeSingle()).data as Slot | null;
  if (!slot) return null;
  const mod = (await db.from("modules").select("id, course_id, title, position").eq("id", slot.module_id).maybeSingle()).data as { id: string; course_id: string; title: string; position: number } | null;
  const course = mod ? ((await db.from("courses").select("id, academy_id, status, version").eq("id", mod.course_id).maybeSingle()).data as { id: string; academy_id: string; status: string; version: number } | null) : null;
  const academy = await academyOf(slug);
  return mod && course && academy && course.academy_id === academy.id ? { slot, mod, course, academy } : null;
}
const targetOf = (s: Slot) => ({ type: "video_slot", id: s.id, label: s.title });
async function viewOf(slotId: string) {
  const db = getDb();
  const slot = (await db.from("video_slots").select("*").eq("id", slotId).maybeSingle()).data as Slot;
  const uploads = (((await db.from("video_uploads").select("*").eq("slot_id", slotId)).data ?? []) as Upload[]).sort((a, b) => b.uploaded_at.localeCompare(a.uploaded_at));
  return slotView(slot as never, uploads as never);
}

const strList = (v: unknown, n: number, each = 300) => (Array.isArray(v) ? v.map((x) => clean(x, each)).filter(Boolean).slice(0, n) : []);

/** Checks a brief the Owner edited: plain text fields, points in order with their sources kept as they were. */
export function checkBrief(input: unknown, before: VideoBrief): { brief: VideoBrief } | { problem: string } {
  const b = (input && typeof input === "object" ? input : {}) as Record<string, unknown>;
  const points = Array.isArray(b.points) ? b.points.slice(0, 12).map((p, i) => {
    const o = (p && typeof p === "object" ? p : {}) as Record<string, unknown>;
    // Sources stay as the Blueprint gave them (from approved sources); an edited or new point keeps or has none.
    const prev = before.points?.[i];
    return { text: clean(o.text, 400), sources: prev && clean(o.text, 400) === prev.text ? prev.sources ?? [] : (Array.isArray(o.sources) ? (prev?.sources ?? []) : []) };
  }).filter((p) => p.text) : [];
  const minutes = b.targetMinutes == null || b.targetMinutes === "" ? null : Number(b.targetMinutes);
  if (minutes !== null && (!Number.isFinite(minutes) || minutes < 1 || minutes > 60)) return { problem: "Target length: 1 to 60 minutes." };
  const brief: VideoBrief = {
    purpose: clean(b.purpose, 500), points, targetMinutes: minutes === null ? null : Math.round(minutes), tone: clean(b.tone, 200),
    onScreen: strList(b.onScreen, 10), avoid: strList(b.avoid, 10),
  };
  if (!brief.points?.length) return { problem: "List at least one point the video must cover." };
  const text = textsOf(brief).join(" ");
  if (ATTORNEY.test(text)) return { problem: NO_ATTORNEY };
  const claim = findIncomeClaims(text)[0];
  if (claim) return { problem: `Reword "${claim.text}": videos never promise income or results.` };
  return { brief };
}

/** Body: any of { title, brief, transcript, lessonId }. The brief is for the Owner (not learners); the transcript is. */
export async function updateSlot(actor: Account, slug: string, slotId: string, body: Record<string, unknown>): Promise<Result> {
  const found = await slotIn(slug, slotId);
  if (!found) return refused(404, "No such video slot in this course.", A);
  const { slot } = found;
  if (actor.roleKey !== "owner") return refused(403, OWNER_ONLY, A, targetOf(slot));
  const fields: Record<string, unknown> = {};
  const changes: string[] = [];
  if (body.title !== undefined) {
    const t = clean(body.title, 200);
    if (t.length < 3) return refused(400, "Give the video a title.", A, targetOf(slot));
    if (findIncomeClaims(t).length || ATTORNEY.test(t)) return refused(400, "Reword the title: no income promises, no \"attorney approved\".", A, targetOf(slot));
    fields.title = t; changes.push("title");
  }
  if (body.brief !== undefined) {
    const c = checkBrief(body.brief, slot.brief ?? {});
    if ("problem" in c) return refused(400, c.problem, A, targetOf(slot));
    Object.assign(fields, { brief: c.brief, brief_generated_by: "person", brief_edited_by_account_id: actor.id, brief_edited_at: new Date().toISOString() });
    changes.push("brief");
  }
  if (body.transcript !== undefined) {
    const t = typeof body.transcript === "string" ? body.transcript.trim().slice(0, 100_000) : "";
    if (findIncomeClaims(t).length) return refused(400, "The transcript has a promise of income or results. Reword the video, or the transcript if it's wrong.", A, targetOf(slot));
    fields.transcript = t || null; changes.push("transcript");
    // Learners read the transcript: a change to an approved video's transcript needs approving again.
    if (slot.status === "approved" && t !== (slot.transcript ?? "")) Object.assign(fields, { status: "uploaded", approved_at: null, approved_by_account_id: null });
  }
  if (body.lessonId !== undefined) {
    if (body.lessonId !== null && !isUuid(body.lessonId)) return refused(400, "Choose a lesson of this module, or none.", A, targetOf(slot));
    fields.lesson_id = body.lessonId; changes.push("position in the module");
  }
  if (!changes.length) return refused(400, "Nothing to change.", A, targetOf(slot));
  const { error } = await getDb().from("video_slots").update(fields).eq("id", slotId);
  if (error) {
    if (/own module/.test(error.message)) return refused(400, "Choose a lesson of this module.", A, targetOf(slot));
    throw new Error(`video slot update failed: ${error.message}`);
  }
  return {
    ok: true, body: await viewOf(slotId),
    event: { action: A, result: "Completed", target: targetOf(slot), previous: slot.status, next: String(fields.status ?? slot.status), context: `Edited the video slot "${slot.title}": ${changes.join(", ")}.${fields.status === "uploaded" ? " Its transcript changed, so the video needs approving again." : ""}` },
  };
}

/** Body: { moduleId, title }. A new, empty slot ("Waiting for video") at the end of the module. */
export async function addSlot(actor: Account, slug: string, body: Record<string, unknown>): Promise<Result> {
  if (actor.roleKey !== "owner") return refused(403, OWNER_ONLY, A);
  const academy = await academyOf(slug);
  if (!academy || !isUuid(body.moduleId)) return refused(404, "No such module in this course.", A);
  const db = getDb();
  const mod = (await db.from("modules").select("id, course_id, title").eq("id", body.moduleId).maybeSingle()).data as { id: string; course_id: string; title: string } | null;
  const course = mod ? ((await db.from("courses").select("academy_id").eq("id", mod.course_id).maybeSingle()).data as { academy_id: string } | null) : null;
  if (!mod || course?.academy_id !== academy.id) return refused(404, "No such module in this course.", A);
  const title = clean(body.title, 200);
  if (title.length < 3) return refused(400, "Give the video a title.", A);
  const slots = ((await db.from("video_slots").select("position").eq("module_id", mod.id)).data ?? []) as { position: number }[];
  if (slots.length >= 4) return refused(409, "A module has at most 4 video slots (the recipe's cap).", A);
  const { data, error } = await db.from("video_slots").insert({ module_id: mod.id, position: Math.max(0, ...slots.map((s) => s.position)) + 1, title, brief: {} }).select("id").single();
  if (error) throw new Error(`video slot insert failed: ${error.message}`);
  const id = (data as { id: string }).id;
  return {
    ok: true, status: 201, body: await viewOf(id),
    event: { action: A, result: "Completed", target: { type: "video_slot", id, label: title }, previous: null, next: "waiting", context: `Added a video slot "${title}" to "${mod.title}". It shows "Video coming" until a video is uploaded and approved.` },
  };
}

/** A slot that never had a file can be removed. */
export async function removeSlot(actor: Account, slug: string, slotId: string): Promise<Result> {
  const found = await slotIn(slug, slotId);
  if (!found) return refused(404, "No such video slot in this course.", A);
  if (actor.roleKey !== "owner") return refused(403, OWNER_ONLY, A, targetOf(found.slot));
  const db = getDb();
  const uploads = ((await db.from("video_uploads").select("id").eq("slot_id", slotId)).data ?? []) as unknown[];
  if (uploads.length) return refused(409, "This slot has had a video uploaded, so it is kept (its upload records stay in the audit trail).", A, targetOf(found.slot));
  const count = ((await db.from("video_slots").select("id").eq("module_id", found.mod.id)).data ?? []) as unknown[];
  if (count.length <= 1) return refused(409, "Every module keeps at least one video slot.", A, targetOf(found.slot));
  const { error } = await db.from("video_slots").delete().eq("id", slotId);
  if (error) throw new Error(`video slot delete failed: ${error.message}`);
  return { ok: true, body: { removed: slotId }, event: { action: A, result: "Completed", target: targetOf(found.slot), previous: "waiting", next: "removed", context: `Removed the empty video slot "${found.slot.title}".` } };
}

/**
 * Step 1 of an upload. Body: { name, size, type }. Checks the size and the declared type, records a pending upload and
 * returns a one-time link the browser sends the file to (straight to Supabase Storage).
 */
export async function startUpload(actor: Account, slug: string, slotId: string, body: Record<string, unknown>): Promise<Result> {
  const found = await slotIn(slug, slotId);
  if (!found) return refused(404, "No such video slot in this course.", A);
  const { slot } = found;
  if (actor.roleKey !== "owner") return refused(403, OWNER_ONLY, A, targetOf(slot));
  const size = Number(body.size);
  if (!Number.isFinite(size) || size <= 0) return refused(400, "Choose a video file.", A, targetOf(slot));
  if (size > VIDEO_MAX_BYTES) return refused(413, tooLarge(size), A, targetOf(slot));
  const name = clean(body.name, 200);
  const declared = String(body.type ?? "");
  const ext = /\.(mp4|webm)$/i.exec(name)?.[1]?.toLowerCase();
  const mime = (declared in VIDEO_TYPES ? declared : ext === "mp4" ? "video/mp4" : ext === "webm" ? "video/webm" : null) as VideoMime | null;
  if (!mime) return refused(415, "Upload an mp4 or webm video.", A, targetOf(slot));
  const id = randomUUID();
  const path = `${slot.id}/${id}.${VIDEO_TYPES[mime]}`;
  const link = await signUpload(path);
  if ("error" in link) return refused(503, "Video storage isn't available right now (is the \"course-videos\" bucket set up?). Nothing was uploaded.", A, targetOf(slot));
  const { error } = await getDb().from("video_uploads").insert({ id, slot_id: slot.id, storage_path: path, mime, size_bytes: Math.round(size), original_name: name || null, uploaded_by_account_id: actor.id });
  if (error) throw new Error(`video upload record failed: ${error.message}`);
  return {
    ok: true, status: 201, body: { uploadId: id, url: link.url, mime, maxBytes: VIDEO_MAX_BYTES },
    event: { action: A, result: "Completed", target: targetOf(slot), previous: slot.status, next: "upload started", context: `Started uploading "${name || "a video"}" (${(size / 1024 / 1024).toFixed(1)} MB) to the slot "${slot.title}".` },
  };
}

/**
 * Step 2, after the browser has sent the file. Reads its first bytes back: it must really be the mp4 or webm it said,
 * and within the size limit. A file that isn't is removed and the upload marked rejected (kept in the trail). An
 * accepted one becomes the slot's video, the previous one is kept as "replaced", and the Owner approves it next.
 */
export async function confirmUpload(actor: Account, slug: string, slotId: string, uploadId: string): Promise<Result> {
  const found = await slotIn(slug, slotId);
  if (!found) return refused(404, "No such video slot in this course.", A);
  const { slot } = found;
  if (actor.roleKey !== "owner") return refused(403, OWNER_ONLY, A, targetOf(slot));
  if (!isUuid(uploadId)) return refused(404, "No such upload.", A, targetOf(slot));
  const db = getDb();
  const up = (await db.from("video_uploads").select("*").eq("id", uploadId).maybeSingle()).data as Upload | null;
  if (!up || up.slot_id !== slot.id) return refused(404, "No such upload.", A, targetOf(slot));
  if (up.status !== "pending") return refused(409, `This upload is already ${up.status}.`, A, targetOf(slot));
  const got = await headOf(up.storage_path);
  const reject = async (why: string) => {
    await removeFile(up.storage_path).catch(() => undefined);
    await db.from("video_uploads").update({ status: "rejected", reject_reason: why, checked_at: new Date().toISOString() }).eq("id", up.id);
    return why;
  };
  if (!got) return refused(409, await reject("The file didn't arrive. Try the upload again."), A, targetOf(slot));
  if (got.size > VIDEO_MAX_BYTES) return refused(413, await reject(tooLarge(got.size)), A, targetOf(slot));
  const real = sniffVideo(got.head);
  if (!real) return refused(415, await reject("That file isn't an mp4 or webm video (checked by its content, not its name)."), A, targetOf(slot));
  if (real !== up.mime) return refused(415, await reject(`That file is really ${real === "video/mp4" ? "an mp4" : "a webm"} video, not what its name says. Rename it and upload again.`), A, targetOf(slot));
  const { data, error } = await db.rpc("accept_video_upload", { p_upload: up.id });
  if (error) throw new Error(`video accept failed: ${error.message}`);
  const previous = data ? String(data) : null;
  return {
    ok: true, body: await viewOf(slot.id),
    event: {
      action: A, result: "Completed", target: targetOf(slot), previous: previous ? `video ${previous} (kept as replaced)` : slot.status, next: "uploaded, waiting for the Owner's approval",
      context: `Uploaded "${up.original_name ?? "a video"}" to "${slot.title}" (${real}, ${(got.size / 1024 / 1024).toFixed(1)} MB, checked by content).${previous ? " It replaces the earlier video, whose record is kept." : ""} It shows to learners only after the Owner approves it.`,
    },
  };
}

/** The Owner approves the slot's uploaded video. It needs a transcript or captions first. */
export async function approveSlot(actor: Account, slug: string, slotId: string): Promise<Result> {
  const found = await slotIn(slug, slotId);
  if (!found) return refused(404, "No such video slot in this course.", A);
  const { slot } = found;
  if (actor.roleKey !== "owner") return refused(403, "Only the Owner approves a video.", A, targetOf(slot));
  if (slot.status === "approved") return refused(409, "This video is already approved.", A, targetOf(slot));
  if (slot.status !== "uploaded" || !slot.current_upload_id) return refused(409, "Upload the video first.", A, targetOf(slot));
  if ((slot.transcript ?? "").trim().length < MIN_TRANSCRIPT_CHARS) return refused(409, "Add the transcript or captions first (paste the text). Learners who can't play or hear the video read it instead.", A, targetOf(slot));
  const { error } = await getDb().from("video_slots").update({ status: "approved", approved_at: new Date().toISOString(), approved_by_account_id: actor.id }).eq("id", slotId);
  if (error) throw new Error(`video approve failed: ${error.message}`);
  return { ok: true, body: await viewOf(slotId), event: { action: A, result: "Completed", target: targetOf(slot), previous: "uploaded", next: "approved", context: `The Owner approved the video "${slot.title}". Learners of the published course can play it.` } };
}

/** A short-lived link for the Owner to watch an uploaded video before approving it. */
export async function previewLink(actor: Account, slug: string, slotId: string) {
  const found = await slotIn(slug, slotId);
  if (!found || actor.roleKey !== "owner" || !found.slot.current_upload_id) return null;
  const up = (await getDb().from("video_uploads").select("storage_path, mime").eq("id", found.slot.current_upload_id).maybeSingle()).data as { storage_path: string; mime: string } | null;
  const url = up ? await signDownload(up.storage_path, VIDEO_LINK_SECONDS) : null;
  return url ? { url, mime: up!.mime, expiresIn: VIDEO_LINK_SECONDS } : null;
}

// ============ Learners ============

/** A slot a learner can see: its module's course is live and open to them, and the lesson that shows it is published. */
async function learnerSlot(actor: Account, slotId: string) {
  if (!isUuid(slotId)) return null;
  const db = getDb();
  const slot = (await db.from("video_slots").select("*").eq("id", slotId).maybeSingle()).data as Slot | null;
  if (!slot) return null;
  const mod = (await db.from("modules").select("id, course_id").eq("id", slot.module_id).maybeSingle()).data as { id: string; course_id: string } | null;
  const course = mod ? ((await db.from("courses").select("id, academy_id, status, unpublished_at").eq("id", mod.course_id).maybeSingle()).data as { id: string; academy_id: string; status: string; unpublished_at: string | null } | null) : null;
  if (!mod || !course || (course.status !== "published" && course.status !== "restored")) return null;
  const academy = (await db.from("academies").select("id, slug").eq("id", course.academy_id).maybeSingle()).data as { id: string; slug: string } | null;
  if (!academy || !(await canOpenCourse(actor, academy, !!course.unpublished_at))) return null;
  const lessons = ((await db.from("lessons").select("id").eq("module_id", mod.id)).data ?? []) as { id: string }[];
  const published = ((await db.from("lesson_versions").select("lesson_id").in("lesson_id", lessons.length ? lessons.map((l) => l.id) : [slot.id]).eq("status", "published")).data ?? []) as { lesson_id: string }[];
  const seen = slot.lesson_id ? published.some((p) => p.lesson_id === slot.lesson_id) : published.length > 0;
  return seen ? slot : null;
}

/** The video slots a lesson shows: its own, and the module's general ones on the module's first lesson. */
export async function lessonVideos(lessonId: string) {
  const db = getDb();
  const lesson = (await db.from("lessons").select("id, module_id, position").eq("id", lessonId).maybeSingle()).data as { id: string; module_id: string; position: number } | null;
  if (!lesson) return [];
  const first = (((await db.from("lessons").select("id, position").eq("module_id", lesson.module_id)).data ?? []) as { id: string; position: number }[]).sort((a, b) => a.position - b.position)[0];
  const slots = (((await db.from("video_slots").select("id, lesson_id, position, title, status, transcript").eq("module_id", lesson.module_id)).data ?? []) as
    { id: string; lesson_id: string | null; position: number; title: string; status: string; transcript: string | null }[])
    .filter((s) => s.lesson_id === lessonId || (!s.lesson_id && first?.id === lessonId)).sort((a, b) => a.position - b.position);
  // Never a fake player: an approved video, or plain "Video coming".
  return slots.map((s) => s.status === "approved"
    ? { id: s.id, title: s.title, state: "ready" as const, transcript: s.transcript ?? "" }
    : { id: s.id, title: s.title, state: "coming" as const, transcript: null });
}

/** A learner's link to an approved video: ten minutes, and only when they may see the lesson it belongs to. */
export async function learnerVideoLink(actor: Account, slotId: string): Promise<Result> {
  const A2 = "learn.video";
  const slot = await learnerSlot(actor, slotId);
  if (!slot) return refused(404, "No such video.", A2);
  if (slot.status !== "approved" || !slot.current_upload_id) return refused(404, "Video coming: this video isn't ready yet.", A2);
  const up = (await getDb().from("video_uploads").select("storage_path, mime").eq("id", slot.current_upload_id).maybeSingle()).data as { storage_path: string; mime: string } | null;
  const url = up ? await signDownload(up.storage_path, VIDEO_LINK_SECONDS) : null;
  if (!url) return refused(503, "The video can't be played right now. Its transcript is below.", A2);
  return { ok: true, body: { id: slot.id, title: slot.title, url, mime: up!.mime, expiresIn: VIDEO_LINK_SECONDS, transcript: slot.transcript ?? "" }, event: { action: A2, result: "Completed", context: "" } };
}
